# Generated by Django 5.1.7 on 2025-03-28 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_service_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрен'),
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(max_length=50, verbose_name='Тип сигнала')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата сигнала')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.review', verbose_name='Отзыв')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сигнал',
                'verbose_name_plural': 'Сигналы',
            },
        ),
    ]
